apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-configmaps-directory-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-configmaps-directory-qa
  template:
    metadata:
      labels:
        app: hello-world-configmaps-directory-qa
    spec:
      containers:
      - name: hello-world
        image: gcr.io/google-samples/hello-app@sha256:2b0febe1b9bd01739999853380b1a939e8102fd0dc5e2ff1fc6892c4557d52b9
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: httpdconfig
            mountPath: "/etc/httpd"
            readOnly: true
      volumes:
        - name: httpdconfig
          configMap:
            name: httpdconfigprod1
