apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-configmaps-files-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-configmaps-files-qa
  template:
    metadata:
      labels:
        app: hello-world-configmaps-files-qa
    spec:
      volumes:
        - name: appconfig
          configMap:
            name: appconfigqa
      containers:
      - name: hello-world
        image: gcr.io/google-samples/hello-app@sha256:2b0febe1b9bd01739999853380b1a939e8102fd0dc5e2ff1fc6892c4557d52b9
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: appconfig
            mountPath: "/etc/appconfig"
