apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-secrets-env-from
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-secrets-env-from
  template:
    metadata:
      labels:
        app: hello-world-secrets-env-from
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/hungtran84/hello-app:1.0
        envFrom:
        - secretRef:
            name: app1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 128M
            cpu: 100m
          limits:
            memory: 128M
            cpu: 100m