apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-secrets-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-secrets-env
  template:
    metadata:
      labels:
        app: hello-world-secrets-env
    spec:
      containers:
      - name: hello-world
        image: gcr.io/google-samples/hello-app@sha256:2b0febe1b9bd01739999853380b1a939e8102fd0dc5e2ff1fc6892c4557d52b9
        env:
        - name: app1username
          valueFrom:
            secretKeyRef:
              name: app1
              key: USERNAME 
        - name: app1password
          valueFrom:
            secretKeyRef:
              name: app1
              key: PASSWORD 
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 128M
            cpu: 100m
          limits:
            memory: 128M
            cpu: 100m
