apiVersion: v1
kind: Service
metadata:
  name: robusta-svc-02
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    robusta: web-app
