apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver
spec:
  storageClassName: gfs
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /vol1
    server: 1.2.3.4
