apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-pod
  template:
    metadata:
      labels:
        app: hello-world-pod
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/hungtran84/hello-app:1.0
